      # -----------------------------
      # Build APK (FORCE SDK + LICENSES)
      # -----------------------------
      - name: Build APK
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk
          ANDROID_HOME: $HOME/android-sdk
          ANDROIDSDK: $HOME/android-sdk
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        run: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          export PATH=$JAVA_HOME/bin:$PATH

          yes | buildozer android debug
